(() => {
  const D=window.SUPPORT_MAP_DATA,app=document.querySelector('#app');
  const state={step:0,selected:{},other:'',deepOpen:false,deepened:false};
  const groups=Object.fromEntries([...D.steps.flatMap(s=>s.groups),D.resourceGroup].map(g=>[g.key,g]));
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const picked=key=>groups[key].options.filter(o=>state.selected[o.id]);
  const labels=key=>picked(key).map(o=>o.label==='その他'&&state.other?`その他（${state.other}）`:o.label);
  const useful=key=>labels(key).filter(x=>!/(まだ|思い当たらない|変化は見られない)/.test(x));
  const quote=(items,max=2)=>items.slice(0,max).map(x=>`「${x}」`).join('、');

  function intro(){return `<section class="intro"><span class="eyebrow">RELAY MINI TOOL</span><h1>支援の手がかりマップ</h1><p>4つの項目から今見えている流れを整理し、明日まず試せそうな一手につなげます。必要なときだけ、強みや条件を追加して詳しく整理できます。</p><aside class="prototype-notice"><b>試作版について</b><span>診断や正解を出すものではなく、支援を考えるための整理ツールです。入力内容は保存されません。児童生徒の氏名など、個人が特定される情報は入力しないでください。</span></aside></section>`}
  function stepper(active){const items=[...D.steps.map(s=>({name:s.short,icon:s.icon})),{name:'かんたん整理',icon:'🔎'}];return `<nav class="stepper" aria-label="3段階の進み具合">${items.map((item,i)=>`<div class="step-item ${i===active?'active':''} ${i<active?'done':''}" ${i===active?'aria-current="step"':''}><span>${i<active?'✓':i+1}</span><b>${item.name}</b>${i===active?'<em>現在</em>':''}</div>`).join('')}</nav>`}
  function progress(n){return `<div class="progress-meta"><span>${n===2?'4項目の整理ができました':`ステップ ${n+1} / 3`}</span><span>${n===2?'かんたん整理':D.steps[n].short}</span></div>`}
  function choices(options){return `<div class="choices">${options.map(o=>`<div class="choice ${o.special?'special':''} ${o.description?'has-description':''}"><input type="checkbox" id="${o.id}" data-id="${o.id}" ${state.selected[o.id]?'checked':''}><label for="${o.id}"><span class="check"></span><span><b class="choice-label">${esc(o.label)}</b>${o.description?`<small class="choice-description">${esc(o.description)}</small>`:''}</span></label>${o.label==='その他'?`<div class="other-field"><label for="otherText">その他の姿を入力してください</label><textarea class="other-input" id="otherText" rows="3">${esc(state.other)}</textarea></div>`:''}</div>`).join('')}</div>`}
  function groupBlock(g){const optionArea=g.sections?g.sections.map(s=>`<div class="choice-category"><h4>${esc(s.title)}</h4>${choices(g.options.slice(s.start,s.start+s.count))}</div>`).join(''):choices(g.options);return `<section class="section-block" data-group="${g.key}">${g.title?`<div class="question-head"><span class="substep">${g.icon||g.number||'＋'}</span><div><h3>${esc(g.title)}</h3><p class="question">${esc(g.question)}</p>${g.helper?`<p class="group-helper">${esc(g.helper)}</p>`:''}</div></div>`:''}${optionArea}<div class="group-warning" data-warning="${g.key}" aria-live="polite"></div></section>`}
  function scrollTo(id){requestAnimationFrame(()=>document.querySelector(id)?.scrollIntoView({behavior:'smooth',block:'start'}))}
  function renderStep(shouldScroll=true){const s=D.steps[state.step],previous=state.step?D.steps[state.step-1].short:'';app.innerHTML=intro()+stepper(state.step)+progress(state.step)+`<section class="card step-card step-theme-${state.step+1}" id="current-step"><div class="step-heading"><span class="step-icon">${s.icon}</span><div><span class="step-kicker">STEP ${state.step+1}</span><h2>${esc(s.title)}</h2></div></div><p class="now-doing">${esc(s.instruction)}</p><p class="lead">${esc(s.lead)}</p>${s.groups.map(groupBlock).join('')}<div class="action-status">ステップ ${state.step+1} / 3</div><div class="actions">${state.step?`<button class="btn btn-secondary" id="prev">前へ：${esc(previous)}に戻る</button>`:''}<span class="hint">当てはまるものを複数選べます。</span><button class="btn btn-primary" id="next">次へ：${esc(s.nextLabel)}</button></div></section>`;bindStep();if(shouldScroll)scrollTo('#current-step')}
  function bindStep(){document.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('change',e=>{state.selected[e.target.dataset.id]=e.target.checked;e.target.closest('.section-block').querySelector('.group-warning').textContent=''}));document.querySelector('#otherText')?.addEventListener('input',e=>state.other=e.target.value);document.querySelector('#prev')?.addEventListener('click',()=>{state.step--;renderStep(true)});document.querySelector('#next').addEventListener('click',()=>{const missing=D.steps[state.step].groups.filter(g=>!g.options.some(o=>state.selected[o.id]));if(missing.length){missing.forEach(g=>document.querySelector(`[data-warning="${g.key}"]`).textContent='この問いで当てはまるものを1つ以上選んでください。');scrollTo(`[data-group="${missing[0].key}"]`);return}state.step++;state.step===2?renderResult():renderStep(true)})}

  function resultData(){
    const scores={},weights={entrance:2,visible:3,before:4,after:3,resources:3};
    Object.entries(groups).forEach(([key,g])=>g.options.filter(o=>state.selected[o.id]).forEach(o=>o.categories.forEach((c,i)=>{scores[c]=(scores[c]||0)+((weights[key]||1)-i*.6)*(o.categoryWeights?.[c]||1)})));
    const top=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]);
    const safeTop=top.length?top:['outlook','communication'];
    return{top:safeTop,relay:[...new Set(safeTop.flatMap(k=>D.categories[k].relay))],jiritsu:[...new Set(safeTop.flatMap(k=>D.categories[k].jiritsu))],memo:buildMemo(safeTop),firstTry:buildFirstTry(safeTop),detail:buildDetail()};
  }
  function functionHint(){const funcs=[...new Set(picked('after').map(o=>o.behaviorFunction).filter(x=>x&&x!=='unknown'))];const hints={avoidance:'その後に負担から離れたり待ってもらえたりする流れから、休憩や助けを早めに選べることが手がかりになりそうです。',attention:'その後に人との関わりが増える流れから、落ち着いた場面で関わりを求められる方法が手がかりになりそうです。',access:'その後に希望するものや助けにつながる流れから、要求や「分からない」を早めに伝えられる方法が手がかりになりそうです。',sensory:'その姿が刺激や気持ちを整えることにつながっている可能性もあり、環境や休み方を見るとよさそうです。'};return funcs.slice(0,1).map(f=>hints[f]).join('')}
  function situationHint(){return [state.selected.a12?'伝えたいことがうまく伝わらない負担が関係している可能性があります。':'',state.selected.a7?'待つ時間の長さや見通しのもちにくさが、気持ちの高まりにつながっている可能性があります。':'',state.selected.a5?'課題の量や難しさ、始め方の分かりにくさが関係しているかもしれません。':'',state.selected.a14?'周囲の刺激の多さが負担になっていた可能性があります。':''].filter(Boolean).join(' ')}
  function buildMemo(top){const entrance=useful('entrance'),visible=useful('visible'),before=useful('before'),after=useful('after');const start=entrance.length?`${quote(entrance,1)}を入口に整理しました。`:'現時点で見えていることから整理しました。';const flow=before.length&&visible.length?`${quote(before)}あとに、${quote(visible)}という姿が見られ${after.length?`、その後に${quote(after)}という`:''}流れが見えています。`:`${quote(visible)}について、前後の状況をもう少し見ると流れが見えやすくなりそうです。`;const view=[situationHint(),functionHint(),D.categories[top[0]].interpretation].filter(Boolean).join(' ');const direction='気持ちや負担が高まってから対応するだけでなく、早めに使える伝え方や、取り組みやすい環境を一つ用意することが手がかりになりそうです。';return[start,flow,view,direction]}
  function isSafety(){return ['b23','b24','b25','b26','b27','b28'].some(id=>state.selected[id])||state.selected.s1_9}
  function buildFirstTry(top){
    if(isSafety())return{suggestions:['気持ちが高まる前に、「離れる」「休む」「伝える」から選べる短い合図を用意する。','人や物との距離を確保できる場所と、そこへ移る合図をあらかじめ決めておく。','要求や拒否を、カード・指さし・短い言葉など本人が使いやすい方法で伝えられるようにする。'],observe:'安全を確保しながら、合図や伝え方を使えた場面と、支援の前後で本人の姿にどんな違いがあったかを見てみましょう。'};
    const suggestions=[...new Set(top.flatMap(k=>D.categories[k].supports))].slice(0,3).map(x=>`${x}。`);
    return{suggestions,observe:'うまくできたかだけでなく、支援を入れた前後で本人の姿にどんな違いがあったかを見てみましょう。'}
  }
  function buildDetail(){const resources=useful('resources');if(!resources.length)return[];const selected=`${quote(resources,3)}が選ばれています。`;let concrete=`${quote(resources,1)}を活動の入口に取り入れ、本人が使いやすい形で始め方や伝え方を示すと、取り組む負担を小さくできそうです。`;if(resources.some(x=>/安心できる人|手本/.test(x)))concrete='活動に入る前に、安心できる人と短く確認したり、手本を見て始めたりすると、取りかかる負担を小さくできそうです。';else if(resources.some(x=>/好きな/.test(x)))concrete='好きなこと・得意なこと・役割を活動の入口に取り入れると、取り組むきっかけになりそうです。';else if(resources.some(x=>/手順|見通し/.test(x)))concrete='始まりと終わり、次の手順を本人に分かりやすい形で先に示すと、見通しをもって取り組みやすくなりそうです。';else if(resources.some(x=>/伝える方法|選択肢/.test(x)))concrete='カード、指さし、短い言葉などから本人が使いやすい伝え方を選べるようにすると、早めに希望や拒否を表しやすくなりそうです。';else if(resources.some(x=>/環境|休憩/.test(x)))concrete='刺激を減らせる場所や短い休憩を選べるようにすると、力を出しやすい状態へ戻る手がかりになりそうです。';return[selected,concrete,'本人が力を出しやすい条件を先に整えることで、参加や気持ちの安定につながる可能性があります。']}
  const resultUsage='この結果は、選択内容をもとにした整理メモです。診断や決めつけではありません。校内で話し合うときや、明日試す支援を考えるときに使ってください。';
  function flowHtml(){const rows=[['その前のきっかけ・状況',labels('before')],['今見えている姿',labels('visible')],['その後に起きていること',labels('after')]];return rows.map((x,i)=>`${i?'<div class="flow-arrow" aria-hidden="true">↓</div>':''}<div class="flow-row"><b>${x[0]}</b><p>${x[1].map(esc).map(v=>`「${v}」`).join(' ')}</p></div>`).join('')}
  function detailHtml(r){if(!state.deepened)return'';return `<section class="detail-results" id="detailed-results"><div class="detail-heading"><div><span class="step-kicker">任意の深掘り結果</span><h3>詳しく整理して見えたこと</h3></div><button class="btn btn-secondary" id="editDeep">強みや条件を編集する</button></div><section class="result-section detail-support"><h3><span>🌱</span>強みや条件を生かした支援</h3><div class="memo-paragraphs">${r.detail.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section><section class="result-section"><h3><span>🏷</span>関連するRELAY実践タグ</h3><div class="tags">${r.relay.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></section><section class="result-section"><h3><span>📘</span>関連しやすい自立活動6区分</h3><div class="tags">${r.jiritsu.map(x=>`<span class="tag jiritsu">${esc(x)}</span>`).join('')}</div></section></section>`}
  function deepHtml(){return `<section class="result-section deepen-section"><h3><span>＋</span>もっと詳しく整理する</h3><p>強みや条件も整理すると、支援の方向をもう少し具体的にできます。<br>必要なときだけ追加できます。</p>${state.deepOpen?`<div class="deep-form">${groupBlock(D.resourceGroup)}<button class="btn btn-primary" id="applyDeep">詳しい結果に更新する</button></div>`:`<button class="btn btn-secondary" id="openDeep">強みや条件を追加する</button>`}</section>`}
  function copyText(r){const lines=['【支援の手がかりマップ】','','【この結果の使い方】',resultUsage,'','【今回見えている流れ】',`その前のきっかけ・状況：${labels('before').join('、')}`,`今見えている姿：${labels('visible').join('、')}`,`その後に起きていること：${labels('after').join('、')}`,'','【見立てメモ】',r.memo.join('\n\n'),'','【まず試すなら】','明日試せそうなことを3つに絞りました。この中から、場面に合いそうなものを1つ選んで試してみてください。','',...r.firstTry.suggestions.map((x,i)=>`${i+1}. ${x}`),'','見ること：',r.firstTry.observe];if(state.deepened)lines.push('','【詳しく整理して見えたこと】',`選んだ強みや条件：${labels('resources').join('、')}`,'','【強みや条件を生かした支援】',r.detail.join('\n\n'),'','【関連するRELAY実践タグ】',...r.relay.map(x=>'・'+x),'','【関連しやすい自立活動6区分】',...r.jiritsu.map(x=>'・'+x));return lines.join('\n')}
  function renderResult(scrollTarget='#current-step'){
    const r=resultData();
    app.innerHTML=intro()+stepper(2)+progress(2)+`<section class="card result-card step-card step-theme-5" id="current-step"><div class="step-heading"><span class="step-icon">🔎</span><div><span class="step-kicker">STEP 3</span><h2>かんたん整理の結果</h2></div></div><p class="now-doing">見えている流れと、明日試せそうなことを確認します。</p><div class="results-grid"><aside class="usage-note result-block"><h3>この結果の使い方</h3><p>${esc(resultUsage)}</p></aside><section class="result-section flow-section"><h3><span>↘</span>今回見えている流れ</h3><div class="flow-map">${flowHtml()}</div></section><section class="result-section memo-section"><h3><span>📝</span>見立てメモ</h3><div class="memo-paragraphs">${r.memo.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section><section class="result-section tomorrow-section"><div class="goal-label">結果の中心</div><h3><span>🌱</span>まず試すなら</h3><div class="first-try"><p class="try-intro">明日試せそうなことを3つに絞りました。<br>この中から、場面に合いそうなものを1つ選んで試してみてください。</p><ol class="try-list">${r.firstTry.suggestions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="try-observe"><b>見ること</b><p>${esc(r.firstTry.observe)}</p></div></div></section>${deepHtml()}${detailHtml(r)}</div><div class="copy-panel"><div><b>校内の記録や共有に</b><small>画面と同じ新しい構成でコピーします。</small></div><button class="btn btn-copy" id="copy">結果をコピー</button></div><div class="copy-status" id="copyStatus" aria-live="polite"></div><div class="actions"><button class="btn btn-secondary" id="back">前へ：姿と背景に戻る</button><button class="btn btn-secondary" id="restart">はじめから整理する</button></div></section>`;
    bindResult(r);scrollTo(scrollTarget);
  }
  function bindResult(r){document.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('change',e=>{state.selected[e.target.dataset.id]=e.target.checked;document.querySelector('[data-warning="resources"]').textContent=''}));document.querySelector('#openDeep')?.addEventListener('click',()=>{state.deepOpen=true;renderResult('.deepen-section')});document.querySelector('#editDeep')?.addEventListener('click',()=>{state.deepOpen=true;renderResult('.deepen-section')});document.querySelector('#applyDeep')?.addEventListener('click',()=>{if(!picked('resources').length){document.querySelector('[data-warning="resources"]').textContent='強みや条件を1つ以上選んでください。';return}state.deepened=true;state.deepOpen=false;renderResult('#detailed-results')});document.querySelector('#back').onclick=()=>{state.step=1;renderStep(true)};document.querySelector('#restart').onclick=()=>{Object.assign(state,{step:0,selected:{},other:'',deepOpen:false,deepened:false});renderStep(true)};document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(copyText(r))}catch{const ta=document.createElement('textarea');ta.value=copyText(r);document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}document.querySelector('#copyStatus').textContent='結果をコピーしました。'} }
  if(window.__SUPPORT_MAP_TEST_MODE__){window.SUPPORT_MAP_TEST={generate(selected={},other='',deepened=false){state.selected={...selected};state.other=other;state.deepened=deepened;const result=resultData();return{result,copy:copyText(result)}}}}else renderStep(false);
})();
