/* RELAY統合を見据え、表示・判定に使う情報をUIロジックから分離しています。 */
window.SUPPORT_MAP_DATA=(()=>{
const o=(id,label,categories=[],special=false,behaviorFunction=null,description='',categoryWeights={})=>({id,label,categories,special,behaviorFunction,description,categoryWeights});
const categories={
outlook:{label:'見通しをもてる支援',relay:['見通しをもつ','手順を身につける','分かりやすく、取り組みやすい環境づくり'],jiritsu:['環境の把握','心理的な安定'],interpretation:'次に起きることや、今すればよいことの分かりにくさが、動きにくさや不安につながっている可能性があります。',supports:['活動の始まりと終わりを、写真・文字・合図のうち本人が分かりやすい方法で示す','「今すること」と「次にすること」を一度に見える形にする','予定変更は、変わるところと変わらないところを分けて伝える']},
difficulty:{label:'活動量・難易度を調整する支援',relay:['手順を身につける','分かりやすく、取り組みやすい環境づくり'],jiritsu:['環境の把握','心理的な安定'],interpretation:'取り組む量や難しさ、始め方を調整すると、もっている力を出しやすくなる可能性があります。',supports:['課題を小さなまとまりに分け、まず終えられる量から試す','最初の一つを一緒に始め、続きは本人が進められるようにする','できているところと負担になっているところを分けて記録する']},
communication:{label:'伝え方を選べる支援',relay:['思いや希望を伝える','選ぶ・決める','やりとりする'],jiritsu:['コミュニケーション','人間関係の形成'],interpretation:'行動だけを止めるより、本人が伝えようとしていることを別の方法で表せるようにすることが手がかりになりそうです。',supports:['「助けて」「休みたい」「分からない」を伝えるカードや言葉の型を用意する','二つ程度の選択肢から、指さしやカードでも選べるようにする','本人が伝えようとした小さなサインを周囲で共有し、早めに応じる']},
environment:{label:'環境や刺激を調整する支援',relay:['分かりやすく、取り組みやすい環境づくり','気持ちを整える'],jiritsu:['環境の把握','心理的な安定'],interpretation:'本人の努力だけに求めず、音、人の多さ、物の配置などを整えることで負担を減らせる可能性があります。',supports:['音・光・人の動きが少ない場所を選べるようにする','座る場所や教材の位置を整え、今必要なものだけを見せる','刺激の多い活動は短時間から始め、退避できる場所を先に確認する']},
calm:{label:'気持ちを落ち着ける支援',relay:['気持ちを整える','見通しをもつ','分かりやすく、取り組みやすい環境づくり'],jiritsu:['心理的な安定','環境の把握'],interpretation:'気持ちが高まってから対応するだけでなく、安心できる方法や休憩を早めに選べるようにすることが役立ちそうです。',supports:['本人が自分で選べる短い休憩や落ち着ける場所を用意する','安心できる人・物・いつもの方法につながれるようにする','落ち着いた後に、次回使えそうな方法を本人と短く確かめる']},
relation:{label:'人との関わりを支える支援',relay:['やりとりする','思いや希望を伝える','選ぶ・決める'],jiritsu:['人間関係の形成','コミュニケーション'],interpretation:'関わる人数や相手、役割を分かりやすくすると、安心してやりとりできる可能性があります。',supports:['慣れた人や少人数で、短いやりとりから始める','誰と何をするか、役割と順番を見える形にする','本人の伝え方を周囲で共有し、返答を待つ時間を確保する']},
interest:{label:'好きなこと・役割を生かす支援',relay:['選ぶ・決める','やりとりする','手順を身につける'],jiritsu:['心理的な安定','人間関係の形成'],interpretation:'好きなことや得意なこと、役割を活動の入口にすると、参加する理由や自信につながる可能性があります。',supports:['好きな題材や得意な方法を、活動の最初の一歩に使う','本人が選べる役割や出番を一つ用意する','できたことを具体的に伝え、達成が本人にも見える形にする']},
daily:{label:'身の回りのことを進める支援',relay:['手順を身につける','手先を使う','見通しをもつ'],jiritsu:['健康の保持','環境の把握','身体の動き'],interpretation:'一連の動作を小さな手順に分け、どこまで自分でできるかを見ると支援量を調整しやすくなりそうです。',supports:['身支度や片付けの手順を、写真や実物で一つずつ示す','道具の置き場所を固定し、自分で確認できるようにする','必要な部分だけ手伝い、自分でできた部分を具体的に確かめる']},
safety:{label:'安全に過ごすための支援',relay:['見通しをもつ','手順を身につける','分かりやすく、取り組みやすい環境づくり'],jiritsu:['健康の保持','環境の把握'],interpretation:'行動が起きてから制止するだけでなく、きっかけを減らし、安全な代わりの行動を用意することが必要そうです。',supports:['危険につながる物や動線を見直し、先に環境を整える','安全な行動を短く具体的に示し、落ち着いた場面で練習する','困ったときに離れる場所や、助けを求める方法を決めておく']},
body:{label:'姿勢・移動・体の使い方に関する環境調整',relay:['身体を使う','手先を使う','分かりやすく、取り組みやすい環境づくり'],jiritsu:['身体の動き','健康の保持','環境の把握'],interpretation:'姿勢や動きの負担を本人の頑張りだけで補うのではなく、教材・環境・活動設定を見直すことが手がかりになりそうです。',supports:['机・椅子・教材の位置や高さを見直し、取り組みやすくする','移動距離や活動時間、道具の持ちやすさを調整する','負担が見られる場面と、楽に取り組める条件を記録して共有する']}};
const entrance=[o('s1_1','活動への参加に支援が必要',['outlook','difficulty','interest']),o('s1_2','気持ちの安定に支援が必要',['calm','environment','outlook']),o('s1_3','予定や活動の切り替えに支援が必要',['outlook','calm']),o('s1_4','困ったことや思いを伝えることに支援が必要',['communication','relation']),o('s1_5','人との関わり方に支援が必要',['relation','communication']),o('s1_6','課題や作業への取り組みに支援が必要',['difficulty','outlook','interest']),o('s1_7','身の回りのことを進めるための支援が必要',['daily','outlook']),o('s1_8','音・人の多さ・環境の変化への支援が必要',['environment','calm']),o('s1_9','安全に過ごすための支援が必要',['safety','calm','environment']),o('s1_10','姿勢・移動・体の使い方に支援が必要',['body','environment']),o('s1_x','どんな支援が必要かまだはっきりしないので、一緒に整理する',[],true)];
const visibleLabels=['活動に入りにくい','始めるまでに時間がかかる','途中で止まる','その場から離れる','取り組みが続きにくい','ぼーっとしている、反応が少ない','寝てしまう、机に伏せる','泣く','怒る','固まる','声が大きくなる','大きな声を出す、叫ぶ','嫌がる、受け入れにくい様子がある','その場で動けなくなる','何度も確認する','同じことを繰り返す','予定や手順の変更を受け入れにくい','困っていることを伝えにくい','要求や拒否を言葉で伝えにくい','友達や先生とのやりとりで困りが見られる','相手との距離が近すぎる、関わりが強くなる','順番やルールを待ちにくい','人の物に触る、取る','手が出る','物を投げる','物を壊す、強く扱う','自分の体をたたく、傷つけるような行動がある','飛び出す、急に走り出す','危険な場所や物に近づく','周囲の刺激に影響されやすい','耳をふさぐ、刺激を避けようとする','姿勢が崩れる','移動や体の使い方に負担がありそう','手先や道具の操作に負担がありそう','その他'];
const visibleCats=[['outlook','difficulty'],['outlook','difficulty'],['difficulty','outlook'],['calm','environment'],['difficulty','interest'],['difficulty','calm'],['calm','body'],['calm','communication'],['calm','safety'],['calm','outlook'],['calm','communication'],['calm','communication'],['calm','environment'],['calm','outlook'],['outlook','calm'],['calm','outlook'],['outlook','calm'],['communication','relation'],['communication','relation'],['relation','communication'],['relation','communication'],['relation','outlook'],['relation','communication'],['safety','calm'],['safety','environment'],['safety','calm'],['safety','calm'],['safety','outlook'],['safety','environment'],['environment','calm'],['environment','calm'],['body','environment'],['body','environment'],['body','daily'],[]];
const visibleDescriptions=['活動場所に入る、輪に加わる、着席することが難しい','席についているが、取りかかるまでに時間がかかる','始めた活動や課題が途中で止まりやすい','活動場所や席から離れることがある','始めても集中や参加が続きにくい','声かけや活動への反応が少ないように見える','活動中に眠る、伏せる、姿勢が大きく崩れる','涙が出る、泣き声が出るなど、気持ちの高まりが見られる','表情や声、行動に怒りや強い不快感が表れる','動きが止まり、表情がこわばる、声かけにも反応しにくくなることがある','普段より声量が大きくなり、気持ちの高まりが見られる','強い声や叫び声で、気持ちや負担を表しているように見える','表情や体の動き、声などで、活動や声かけを受け入れにくい様子が見られる','緊張した様子が見られ、移動や次の行動に移りにくくなる','同じことを繰り返し聞いたり、確認したりする','同じ言葉、動き、行動を繰り返す','予定や手順が変わると、不安定になったり動きにくくなったりする','困っていても、言葉や行動で伝えることが難しい','「したい」「いや」「やめたい」などを言葉で伝えにくい','会話、遊び、活動の中で、相手との関わりに支援が必要に見える','相手に近づきすぎる、強く触れる、関わりが一方的になることがある','順番、交代、約束、ゲームのルールなどを待つことが難しい','相手の持ち物や教材に触ったり、取ったりすることがある','人を押す、たたく、つかむなど、人に向かう行動が見られる','持っている物や近くの物を投げることがある','物を強く扱う、壊す、乱暴に動かすことがある','自分の体に強く触れる、たたくなど、安全面で心配な姿が見られる','急にその場を離れたり、走り出したりすることがある','道路、階段、刃物、熱い物など、危険につながる場所や物に近づくことがある','音、人の動き、光、においなどに影響されやすい','音や人の多さなどを避けようとする姿が見られる','座位や立位の姿勢が崩れやすく、活動に影響しているように見える','歩く、立つ、座る、体を動かすことに負担がありそうに見える','鉛筆、はさみ、道具、教材の操作に難しさや負担がありそうに見える','上の項目に近いものがない場合に、自由記述で入力する'];
const beforeLabels=['急な予定変更があった','活動の始まりや終わりだった','次に何をするか分かりにくかった','見通しがもてないまま活動が始まった','場所や座席が変わった','課題が難しかった','課題量が多かった','待つ時間が長かった','注意や指示を受けた','長い説明や口頭指示が続いた','周囲のペースが速かった','自分で選べる場面が少なかった','伝えたいことが伝わりにくかった','人が多かった','音や刺激が多かった','苦手な相手や活動があった','好きな活動が終わった','体調や疲れがありそうだった','特に思い当たらない','まだよく分からない'];
const beforeCats=[['outlook','calm'],['outlook'],['outlook'],['outlook'],['environment','outlook'],['difficulty'],['difficulty'],['outlook','calm'],['relation','communication'],['communication','difficulty'],['difficulty','calm'],['communication','interest'],['communication'],['environment','relation'],['environment'],['relation','environment'],['outlook','calm'],['calm','body'],[],[]];
const afterLabels=['活動から離れられる','課題や要求が少なくなる','大人が近くに来る','声をかけてもらえる','好きなものや活動に移れる','待ってもらえる','別の場所で落ち着ける','やり方を教えてもらえる','本人の要求が通る','周囲が本人に合わせて動く','その行動をすることで、本人が落ち着くように見える','特に変化は見られない','まだよく分からない'];
const afterCats=[['difficulty','communication'],['difficulty'],['relation','communication'],['relation'],['interest','communication'],['outlook','calm'],['calm','environment'],['outlook','difficulty'],['communication'],['communication','relation'],['calm','environment'],[],[]];
const afterFunctions=['avoidance','avoidance','attention','attention','access','avoidance','avoidance','access','access','attention','sensory','unknown','unknown'];
const lessLabels=['慣れた人と一緒のとき','見通しがあるとき','好きな活動のとき','静かな場所のとき','少人数のとき','活動量が少ないとき','自分で選べるとき','手本があるとき','休憩できるとき','まだよく分からない'];
const lessCats=[['relation','calm'],['outlook'],['interest'],['environment'],['relation','environment'],['difficulty'],['communication','interest'],['difficulty','outlook'],['calm','environment'],[]];
const strengthsLabels=['好きなことや興味をもてることがある','得意なことや自信をもてることがある','人の様子をよく見ている','手本を見てまねることができる','決まった言い方や方法を覚えることができる','慣れると自分から取り組める','役割があると張り切る','人に伝えようとする姿がある','自分なりに落ち着こうとする方法がある','以前できた経験がある','好きな人、安心できる人がいる','まだ生かせそうな強みがはっきりしない'];
const strengthsCats=[['interest'],['interest'],['relation'],['difficulty','body'],['communication','outlook'],['outlook','interest'],['interest','relation'],['communication','relation'],['calm'],['difficulty','interest'],['relation','calm'],[]];
const conditionsLabels=['活動の始まりと終わりが分かる','次にすることや手順が見える','量や時間の見通しがある','写真・絵・文字などの手がかりがある','実物や具体物で確認できる','選択肢がある','伝え方の型やカードがある','静かで刺激の少ない環境で取り組める','座る場所や教材の位置が整っている','慣れた人や少人数の中で取り組める','好きな活動や役割とつながっている','休憩や落ち着ける場所がある','できたことがすぐ分かる','まだ条件がはっきりしない'];
const conditionsCats=[['outlook'],['outlook','daily'],['outlook','difficulty'],['outlook','communication'],['difficulty','daily'],['communication','interest'],['communication'],['environment'],['environment','body'],['relation','calm'],['interest'],['calm','environment'],['interest','difficulty'],[]];
const make=(prefix,labels,cats,functions=[],descriptions=[])=>labels.map((x,i)=>o(prefix+i,x,cats[i],/まだ|その他/.test(x),functions[i]||null,descriptions[i]||''));
const visibleOptions=make('b',visibleLabels,visibleCats,[],visibleDescriptions);
visibleOptions[0]=o('b0','活動の場に入りにくい',['outlook','environment','calm','relation'],false,null,'活動場所に入る、輪に加わる、着席することが難しい',{outlook:1.35,environment:1.25,calm:1.2,relation:1.1});
visibleOptions[1]=o('b1','活動に入っても始めにくい',['outlook','difficulty','interest'],false,null,'席についているが、取りかかるまでに時間がかかる',{outlook:1.35,difficulty:1.3,interest:1.15});
visibleOptions[23]=o('b23','手が出る',['relation','calm','communication','safety'],false,null,visibleDescriptions[23],{relation:1.3,calm:1.2,communication:1.2,safety:1.1});
visibleOptions[24]=o('b24','物を投げる',['safety','environment','difficulty','calm'],false,null,visibleDescriptions[24],{safety:1.35,environment:1.2,difficulty:1.15,calm:1.1});
const sections=(titles,counts)=>titles.map((title,i)=>({title,start:counts.slice(0,i).reduce((a,b)=>a+b,0),count:counts[i]}));
const steps=[
{short:'支援を考えたいこと',icon:'🧭',title:'支援を考えたいこと',lead:'今、一緒に整理したいことを入口として選びます。まだはっきりしない場合も、ここから考え始められます。',key:'entrance',options:entrance},
{short:'今見えている姿',icon:'👀',title:'今見えている姿',lead:'評価や解釈ではなく、実際に見えている姿を観察メモとして選びます。',key:'visible',sections:sections(['参加・取り組み','気持ち・切り替え','伝える・確認する','人との関わり','安全面で心配な姿','感覚・身体','その他'],[7,7,5,4,6,5,1]),options:visibleOptions},
{short:'その前の状況',icon:'⏪',title:'その前のきっかけ・状況',lead:'その姿の直前にあったことを振り返ります。場所、人、課題、伝わり方、刺激などに目を向けます。',key:'before',sections:sections(['見通し・変更','課題・要求','選択・伝達','人・環境刺激','好み・切り替え','身体・状態','未整理'],[5,6,2,3,1,1,2]),options:make('a',beforeLabels,beforeCats)},
{short:'その後のこと',icon:'⏩',title:'その後に起きていること',lead:'その姿のあと、本人にとって何が起きていることが多いかを整理します。ここまでで、まず結果を確認できます。',key:'after',options:make('c',afterLabels,afterCats,afterFunctions)}];
const deepDive=[
{key:'strengths',title:'本人の強み',lead:'好きなこと、できていること、安心できる人や方法を整理します。',options:make('st',strengthsLabels,strengthsCats)},
{key:'conditions',title:'力を発揮しやすい条件',lead:'時間、場所、人、教材、手順、刺激量など、周囲が整えられる条件を考えます。',options:make('co',conditionsLabels,conditionsCats)}];
return{categories,steps,deepDive,bodyNotice:'姿勢・移動・体の使い方に関する支援は、身体の状態や安全面と関わります。RELAYでは、教材の位置、机や椅子、活動量、休憩の入れ方など、教材・環境・活動設定の工夫を支援の手がかりとして扱います。身体への直接的な手技、動作法、体の緩め、移乗介助、装具調整などは、専門性のある教員、養護教諭、PT・OT等と相談しながら進めてください。'};
})();
